"""
Train an XGBoost classifier for ticket priority prediction.

Loads the fully-deterministic priority_training.csv generated by
prepare_priority_data.py (Bitext raw data + VADER + MiniLM anchors + Bitext
linguistic flags + synthetic tabular context) and fits a cost-sensitive
gradient-boosted tree model.

Logs every run to MLflow (local file store at ./mlflow/).
"""
import os
import json

import mlflow
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.utils.class_weight import compute_class_weight

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
TRAINING_DATA_DIR = os.path.join(PROJECT_ROOT, "training_data")
MODEL_DIR = os.path.join(PROJECT_ROOT, "models", "priority_model")
MLFLOW_TRACKING_URI = os.path.join(PROJECT_ROOT, "mlflow")

PRIORITY_LABELS = ["Low", "Medium", "High", "Urgent"]

CATEGORICAL_FEATURES = ["category", "customer_tier", "source_channel"]

# Excluded features: business_impact_score, vader_neg, vader_compound,
# is_sla_breached, has_negative_flag, has_emotional_flag, has_typo_flag,
# has_multi_issue_flag, threat_language_ratio, sim_urgent_anchor,
# sim_critical_anchor, sla_hours_remaining.
# These are literal inputs to the label formula (compute_priority_score);
# training on them let the model reconstruct the formula (92.7% accuracy)
# instead of learning real patterns.

NUMERIC_FEATURES = [
    "vader_neu", "vader_pos",
    "sim_frustrated_anchor", "sim_routine_anchor",
    "urgency_keyword_ratio", "time_pressure_ratio",
    "frustration_negation_ratio", "profanity_ratio", "exclamation_ratio",
    "question_ratio", "caps_word_ratio", "text_length_words", "text_length_chars",
    "has_context_flag", "has_imperative_flag", "has_question_flag",
    "has_polite_flag", "has_knowledge_flag", "has_basic_flag", "has_long_flag", "flag_count",
    "ticket_age_hours", "repeat_contact_count",
    "interact_age_frustration",
    "interact_age_frustrated_anchor",
    "interact_age_question",
    "interact_repeats_flags",
]

FEATURES = CATEGORICAL_FEATURES + NUMERIC_FEATURES

RANDOM_STATE = 42

XGB_PARAMS = {
    "n_estimators": 300,
    "max_depth": 3,
    "learning_rate": 0.05,
    "reg_lambda": 1.0,
    "min_child_weight": 2,
}


def prep_features(df: pd.DataFrame) -> pd.DataFrame:
    X = df[FEATURES].copy()
    for col in CATEGORICAL_FEATURES:
        X[col] = X[col].astype("category")
    return X


def main():
    print("=" * 65)
    print("  TRAINING — XGBoost Priority Classifier (deterministic features)")
    print("=" * 65)

    csv_path = os.path.join(TRAINING_DATA_DIR, "priority_training.csv")
    print(f"\n[1] Loading data from {csv_path}")
    df = pd.read_csv(csv_path)
    print(f"    Rows: {len(df):,}")

    label2id = {label: idx for idx, label in enumerate(PRIORITY_LABELS)}
    df["label"] = df["priority"].map(label2id)

    train_df = df[df["split"] == "train"].copy()
    test_df = df[df["split"] == "test"].copy()
    print(f"\n[2] Train: {len(train_df):,}  |  Test: {len(test_df):,}")
    print(f"    Features ({len(FEATURES)}): {FEATURES}")

    X_train = prep_features(train_df)
    X_test = prep_features(test_df)
    y_train = train_df["label"].values
    y_test = test_df["label"].values

    print("\n[3] Computing cost-sensitive class weights...")
    class_ids = np.arange(len(PRIORITY_LABELS))
    class_weights = compute_class_weight(class_weight="balanced", classes=class_ids, y=y_train)
    print("    Class weights:")
    for label, w in zip(PRIORITY_LABELS, class_weights):
        count = int((y_train == label2id[label]).sum())
        print(f"      {label:<10} weight={w:.3f}  (n={count:,})")
    weight_per_id = {i: w for i, w in enumerate(class_weights)}
    sample_weight_train = np.array([weight_per_id[y] for y in y_train])

    print("\n[4] Training XGBoost classifier (cost-sensitive)...")
    model = xgb.XGBClassifier(
        **XGB_PARAMS,
        objective="multi:softprob",
        num_class=len(PRIORITY_LABELS),
        eval_metric="mlogloss",
        enable_categorical=True,
        random_state=RANDOM_STATE,
        early_stopping_rounds=20,
    )
    model.fit(
        X_train, y_train,
        sample_weight=sample_weight_train,
        eval_set=[(X_test, y_test)],
        verbose=50,
    )

    print("\n[5] Evaluating on test set...")
    preds = model.predict(X_test)
    acc = accuracy_score(y_test, preds)
    f1_macro = f1_score(y_test, preds, average="macro")
    f1_weighted = f1_score(y_test, preds, average="weighted")
    print(f"    Accuracy:      {acc:.4f}")
    print(f"    F1 (macro):    {f1_macro:.4f}")
    print(f"    F1 (weighted): {f1_weighted:.4f}")

    print("\n[6] Detailed classification report:")
    report = classification_report(
        y_test, preds, labels=list(range(len(PRIORITY_LABELS))),
        target_names=PRIORITY_LABELS, zero_division=0,
    )
    print(report)
    report_path = os.path.join(MODEL_DIR, "classification_report.txt")
    with open(report_path, "w") as f:
        f.write(report)
    print(f"    Saved classification report: {report_path}")

    print("\n[7] Feature importances:")
    importances = sorted(
        zip(FEATURES, model.feature_importances_), key=lambda x: -x[1]
    )
    for feat, imp in importances:
        print(f"      {feat:<30} {imp:.4f}")

    print(f"\n[8] Saving model to {MODEL_DIR}")
    model_path = os.path.join(MODEL_DIR, "model.json")
    model.save_model(model_path)
    print(f"    Saved model: {model_path}")

    metrics = {
        "accuracy": float(acc),
        "f1_macro": float(f1_macro),
        "f1_weighted": float(f1_weighted),
        "num_train_samples": len(train_df),
        "num_test_samples": len(test_df),
        "num_classes": len(PRIORITY_LABELS),
        "classes": PRIORITY_LABELS,
        "features": FEATURES,
        "feature_importances": {feat: float(imp) for feat, imp in importances},
        "model_type": "XGBClassifier",
        "n_estimators": model.n_estimators,
        "max_depth": model.max_depth,
        "learning_rate": model.learning_rate,
        "reg_lambda": model.reg_lambda,
        "min_child_weight": model.min_child_weight,
        "best_iteration": int(model.best_iteration) if hasattr(model, "best_iteration") else None,
        "cost_sensitive_class_weights": {label: float(w) for label, w in zip(PRIORITY_LABELS, class_weights)},
    }
    metrics_path = os.path.join(MODEL_DIR, "metrics.json")
    with open(metrics_path, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"    Saved metrics: {metrics_path}")

    # ── MLflow logging ──────────────────────────────────────────────────
    mlflow.set_tracking_uri("file:///" + MLFLOW_TRACKING_URI.replace("\\", "/"))
    with mlflow.start_run(run_name="priority_xgboost"):
        mlflow.log_params({
            "model_type": "XGBClassifier",
            "objective": "multi:softprob",
            "num_features": len(FEATURES),
            "feature_list": json.dumps(FEATURES),
            **XGB_PARAMS,
        })
        mlflow.log_params({
            f"weight_{label}": float(w)
            for label, w in zip(PRIORITY_LABELS, class_weights)
        })

        mlflow.log_metrics({
            "accuracy": float(acc),
            "f1_macro": float(f1_macro),
            "f1_weighted": float(f1_weighted),
        })

        importances_dict = {feat: float(imp) for feat, imp in importances}
        with open(os.path.join(MODEL_DIR, "feature_importances.json"), "w") as f:
            json.dump(importances_dict, f, indent=2)
        mlflow.log_artifact(os.path.join(MODEL_DIR, "feature_importances.json"))
        mlflow.log_artifact(report_path)
        mlflow.log_artifact(metrics_path)
        mlflow.log_artifact(model_path)

        print(f"    MLflow run: {mlflow.active_run().info.run_id}")

    print(f"\n{'=' * 65}")
    print(f"  DONE — Model saved to {MODEL_DIR}")
    print(f"  Accuracy: {metrics['accuracy']:.2%}  |  F1 (macro): {metrics['f1_macro']:.2%}")
    print(f"{'=' * 65}")


if __name__ == "__main__":
    main()
